// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    InlineSelector: typeof import('./components/InlineSelector.vue')['default']
    InsulationSelector: typeof import('./components/InsulationSelector.vue')['default']
    PhaseSelector: typeof import('./components/PhaseSelector.vue')['default']
    PowerOptions: typeof import('./components/PowerOptions.vue')['default']
    RadioGroup: typeof import('./components/RadioGroup.vue')['default']
    RadioOption: typeof import('./components/RadioOption.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Surface: typeof import('./components/Surface.vue')['default']
    Textfield: typeof import('./components/Textfield.vue')['default']
    VoltageSelector: typeof import('./components/VoltageSelector.vue')['default']
  }
}
